// Code generated by "stringer -type=ValueType"; DO NOT EDIT.

package jscan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueTypeObject-1]
	_ = x[ValueTypeArray-2]
	_ = x[ValueTypeNull-3]
	_ = x[ValueTypeFalse-4]
	_ = x[ValueTypeTrue-5]
	_ = x[ValueTypeString-6]
	_ = x[ValueTypeNumber-7]
}

const _ValueType_name = "ValueTypeObjectValueTypeArrayValueTypeNullValueTypeFalseValueTypeTrueValueTypeStringValueTypeNumber"

var _ValueType_index = [...]uint8{0, 15, 29, 42, 56, 69, 84, 99}

func (i ValueType) String() string {
	i -= 1
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
